<!DOCTYPE html>
<html>

<head>
    <title>Laporan Absensi Cabang</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        .logo {
            width: 80px;
            height: auto;
            margin-bottom: 10px;
        }

        .title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .subtitle {
            font-size: 14px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .text-left {
            text-align: left;
        }

        .footer {
            margin-top: 40px;
            width: 100%;
        }

        .signature-box {
            width: 30%;
            display: inline-block;
            text-align: center;
            vertical-align: top;
        }

        .signature-line {
            margin-top: 60px;
            border-top: 1px solid #000;
            display: inline-block;
            width: 80%;
        }
    </style>
</head>

<body>
    <div class="header">
        {{-- Menggunakan path absolute untuk image di PDF --}}
        <img src="{{ public_path('assets/images/logo-pstore.png') }}" class="logo" alt="PStore Logo">
        <div class="title">LAPORAN ABSENSI KUNJUNGAN RUTIN</div>
        <div class="subtitle">Cabang: {{ $branch->name }} | Periode: {{ $monthName }}</div>
        <div class="subtitle" style="font-size: 10px; margin-top: 5px;">Generated by: {{ $generatedBy->name }}
            ({{ strtoupper($generatedBy->role) }})</div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th width="5%">No</th>
                <th width="35%">Nama Karyawan</th>
                <th width="10%">Hadir</th>
                <th width="10%">Sakit</th>
                <th width="10%">Izin</th>
                <th width="10%">Alfa</th>
                <th width="10%">Libur</th>
                <th width="10%">Telat</th>
                <th width="10%">Total Jam</th>
            </tr>
        </thead>
        <tbody>
            @forelse($data as $index => $row)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td class="text-left">
                        <strong>{{ $row['user']->name }}</strong><br>
                        <small style="color: #666;">{{ $row['user']->job_title ?? 'Staff' }}</small>
                    </td>
                    <td>{{ $row['summary']['hadir'] }}</td>
                    <td>{{ $row['summary']['sakit'] }}</td>
                    <td>{{ $row['summary']['izin'] }}</td>
                    <td>{{ $row['summary']['alfa'] }}</td>
                    <td>{{ $row['summary']['libur'] }}</td>
                    <td>{{ $row['summary']['telat'] }}</td>
                    <td>{{ number_format($row['summary']['total_jam'], 1) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9">Tidak ada data karyawan di cabang ini.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <div class="signature-box">
            <p>Mengetahui,</p>
            <br>
            <div class="signature-line"></div>
            <p>Kepala Cabang / Leader</p>
        </div>

        <div class="signature-box" style="float: right;">
            <p>Dibuat Oleh,</p>
            <br>
            <div class="signature-line"></div>
            <p>{{ $generatedBy->name }} (Audit)</p>
        </div>
    </div>
</body>

</html>